// bomb_texts.h —— 库巴传炸弹的全部文案。字库从这里收集字符;.c 里不写中文。
#pragma once

#define BX_TITLE "库巴传炸弹"
#define BX_SUB "炸弹传来传去，谁炸谁输"
#define BX_CPU "和电脑打"
#define BX_LINK "两人联机"
#define BX_BACK "回菜单"
#define BX_WINS "赢了 %u 场"
#define BX_SEARCH "正在找对方……"
#define BX_SEARCH2 "让对方也按「两人联机」"
#define BX_SEARCH3 "两张卡靠近一点"
#define BX_HOME_HINT "● 回首页"
#define BX_NO_MEM "内存不够"
#define BX_NO_MEM2 "先退出游戏再进来"
#define BX_BAD_VER "版本不一样"
#define BX_BAD_VER2 "两张卡都去商店更新"
#define BX_LOST "对方走开了"
#define BX_LOST2 "正在等他回来……"
#define BX_SCORE "%u : %u"
#define BX_ROUND "第 %u 回合"
#define BX_CATCH "接住！"
#define BX_AWAY "在对方手里"
#define BX_FLY "飞过去啦！"
#define BX_BOOM_ME "炸了！"
#define BX_BOOM_PEER "对方炸了！"
#define BX_WIN "你赢了！"
#define BX_LOSE "对方赢了"
#define BX_AGAIN "● 再来  ▼ 回首页"
#define BX_WAIT_AGAIN "等对方按 ●"
#define BX_HOT "快扔！"
#define BX_MISS "扔歪了！"
#define BX_PERFECT "完美！"

// 选人页
#define BX_PICK "选你的人"
#define BX_PICK_HINT "▲▼ 选  ● 确定"
#define BX_PICK_WAIT "等对方选……  ▼ 重选"
#define BX_PEER_PICKING "对方还在选"
#define BX_PEER_PICKED "对方选了%s"
#define BX_HOME "回首页"

// 角色名、招式名(下标 = bomb_fighter_t)
#define BX_KID "库巴"
#define BX_DAD "库巴爸爸"
#define BX_GRANNY "库巴奶奶"
#define BX_GRANDPA "库巴爷爷"
#define BX_SK_SLING "弹弓"
#define BX_SK_DECOY "影分身"
#define BX_SK_ROCKET "火箭快递"
#define BX_SK_CAGE "铁笼"
#define BX_SK_NAG "念叨"
#define BX_SK_LID "锅盖神功"
#define BX_SK_GLASSES "老花镜"
#define BX_SK_TAIJI "太极推手"
#define BX_SK_LID_BIG "锅盖神功！"
#define BX_SK_TAIJI_BIG "太极推手！"

// 游戏页提示行
#define BX_KEY_THROW "● 扔"
#define BX_KEY_SPECIAL "  ▲ %s"   // 能量够了才显示
#define BX_KEY_SUPER "  ▼ %s"
#define BX_CAGE_HINT "狂按 ● 砸笼子 %u"
#define BX_DECOY_HINT "▲▼ 选炸弹  ● 扔"
#define BX_GLASSES_N "老花镜 %u"

// 和电脑打(闯关)
#define BX_STAGE "第 %u 关"
#define BX_NEXT "● 下一关  ▼ 回首页"
#define BX_RETRY "● 再打一次  ▼ 回首页"
#define BX_CLEAR "通关！"
#define BX_CLEAR_HINT "● 再闯一次  ▼ 回首页"
