// bomb_texts.h —— 库巴传炸弹的全部文案。字库从这里收集字符;.c 里不写中文。
#pragma once

#define BX_TITLE "库巴传炸弹"
#define BX_SUB "炸弹传来传去，谁炸谁输"
#define BX_START "开始"
#define BX_BACK "回菜单"
#define BX_WINS "赢了 %u 场"
#define BX_SEARCH "正在找对方……"
#define BX_SEARCH2 "让对方也按「开始」"
#define BX_SEARCH3 "两张卡靠近一点"
#define BX_HOME_HINT "● 回首页"
#define BX_NO_MEM "内存不够"
#define BX_NO_MEM2 "先退出游戏再进来"
#define BX_BAD_VER "版本不一样"
#define BX_BAD_VER2 "两张卡都更新到最新再玩"
#define BX_LOST "对方走开了"
#define BX_LOST2 "正在等他回来……"
#define BX_SCORE "你 %u : %u 对方"
#define BX_ROUND "第 %u 回合"
#define BX_THROW "● 扔过去！"
#define BX_CATCH "接住！"
#define BX_AWAY "在对方手里"
#define BX_FLY "飞过去啦！"
#define BX_BOOM_ME "炸了！"
#define BX_BOOM_PEER "对方炸了！"
#define BX_WIN "你赢了！"
#define BX_LOSE "对方赢了"
#define BX_AGAIN "● 再来  ▼ 回首页"
#define BX_WAIT_AGAIN "等对方按 ●"
#define BX_HOT "快扔！"
